Repository CMPUT301W21T03/Experiment-Automata, pull requests merged in 2021-03, with the labels that each got.

#58 User stub
  code/.idea/gradle.xml
  code/app/src/main/java/com/example/experiment_automata/ContactInformation.java
  code/app/src/main/java/com/example/experiment_automata/User.java
Labels: Product Backlog

#59 firebase setup
  code/.idea/gradle.xml
  code/app/.gitignore
  code/app/build.gradle
  code/build.gradle
Labels: Product Backlog

#67 Update user
  code/app/build.gradle
  code/app/src/main/java/com/example/experiment_automata/ContactInformation.java
  code/app/src/main/java/com/example/experiment_automata/User.java
Labels: Product Backlog

#69 Create android.yml
  .github/workflows/android.yml
Labels: enhancement

#70 create user from UUID
  code/app/src/main/java/com/example/experiment_automata/User.java
Labels: enhancement

#76 search experiments
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/experiment_automata/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  code/app/src/main/res/layout/fragment_add_experiment.xml
  code/app/src/main/res/navigation/mobile_navigation.xml
  code/app/src/main/res/values/strings.xml
  code/app/src/main/res/xml/searchable.xml
Labels: Product Backlog

#81 Add trial
  code/app/src/main/java/com/example/experiment_automata/AddExperimentFragment.java
  code/app/src/main/java/com/example/experiment_automata/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/ExperimentMaker.java
  code/app/src/main/java/com/example/experiment_automata/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/trials/BinomialTrial.java
  code/app/src/main/java/com/example/experiment_automata/trials/CountTrial.java
  code/app/src/main/java/com/example/experiment_automata/trials/MeasurementTrial.java
  code/app/src/main/java/com/example/experiment_automata/trials/NaturalCountTrial.java
  code/app/src/main/java/com/example/experiment_automata/trials/Trial.java
  code/app/src/test/java/com/example/experiment_automata/ExampleUnitTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentMakerTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentMakerTests.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentManagerTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentTest.java
  code/app/src/test/java/com/example/experiment_automata/TrialTest.java
Labels: Product Backlog

#92 Display stats
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
  code/app/src/main/res/layout/fragment_statistics.xml
  code/app/src/main/res/values/strings.xml
  code/app/src/test/java/com/example/experiment_automata/BinomialExperimentStatTest.java
  code/app/src/test/java/com/example/experiment_automata/MeasurementStatTest.java
  code/app/src/test/java/com/example/experiment_automata/NaturalCountStatTest.java
Labels: Product Backlog

#95 Display graphs
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Graphable.java
  code/app/src/main/res/layout/fragment_histogram.xml
  code/app/src/main/res/layout/fragment_nav_experiment_details.xml
  code/app/src/main/res/layout/fragment_results.xml
  code/app/src/main/res/values/dimens.xml
Labels: Product Backlog

#98 Updated UML diagram, slightly refactored code, and got rid of the sub…
  code/app/src/androidTest/java/com/example/experiment_automata/ExampleInstrumentedTest.java
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/Subscription.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/StatSummary.java
  code/app/src/main/java/com/example/experiment_automata/trials/CountTrial.java
  code/app/src/test/java/com/example/experiment_automata/SubscriptionTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: documentation

#99 Fixing tests
  code/app/build.gradle
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/SearchUserStoriesTests.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/ExperimentMaker.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/QuestionUI/QuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/QuestionsModel/QuestionController.java
  code/app/src/main/java/com/example/experiment_automata/QuestionsModel/QuestionManager.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentManagerTest.java
  code/app/src/test/java/com/example/experiment_automata/QuestionManagerTest.java
  code/app/src/test/java/com/example/experiment_automata/QuestionTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: enhancement

#104 Ignore trials
  code/app/src/androidTest/java/com/example/experiment_automata/BinomialTrialTests.java
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/TrialArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ExperimentFragments/TrialsFragment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/trials/Trial.java
  code/app/src/main/res/layout/fragment_nav_experiment_details.xml
  code/app/src/main/res/layout/fragment_trials.xml
  code/app/src/main/res/layout/trial_layout.xml
  code/app/src/test/java/com/example/experiment_automata/BinomialExperimentStatTest.java
  code/app/src/test/java/com/example/experiment_automata/MeasurementStatTest.java
  code/app/src/test/java/com/example/experiment_automata/NaturalCountStatTest.java
  code/app/src/test/java/com/example/experiment_automata/TrialTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog

#105 User profile
  code/app/src/main/java/com/example/experiment_automata/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/UserInformation/ContactInformation.java
  code/app/src/main/java/com/example/experiment_automata/UserInformation/User.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileViewModel.java
  code/app/src/main/res/drawable/ic_baseline_email.xml
  code/app/src/main/res/drawable/ic_baseline_phone.xml
  code/app/src/main/res/layout/fragment_profile.xml
  code/app/src/main/res/values/strings.xml
  code/app/src/test/java/com/example/experiment_automata/UserTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog

#101 Search refinement
  code/app/src/main/java/com/example/experiment_automata/Experiments/ExperimentModel/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentManagerTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: enhancement

#111 Edit user
  code/app/src/main/java/com/example/experiment_automata/backend/users/ContactInformation.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/EditUserFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileViewModel.java
  code/app/src/main/res/layout/fragment_edit_user.xml
Labels: Product Backlog

#113 Qr code refactor
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRType.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ViewQRFragment.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog

#114 User intent test
  code/app/src/androidTest/java/com/example/experiment_automata/UserTests.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/res/layout/fragment_profile.xml
Labels: enhancement

#119 Link trial experimenter profile
  code/app/src/androidTest/java/com/example/experiment_automata/BinomialTrialTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/SearchUserStoriesTests.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/ui/LinkView.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/QuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
  code/app/src/main/res/layout/app_bar_main.xml
  code/app/src/main/res/layout/fragment_profile.xml
  code/app/src/main/res/layout/link_view.xml
  code/app/src/main/res/layout/trial_layout.xml
  code/app/src/main/res/values/attrs_link_view.xml
Labels: Product Backlog

#120 Link Q&A user profile
  code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
  code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/ui/LinkView.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/ReplyArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/SingleQuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
  code/app/src/main/res/layout/main_question_display.xml
  code/app/src/main/res/layout/reply_layout_list.xml
Labels: Product Backlog

#124 Subscribe
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/res/drawable/ic_baseline_star.xml
  code/app/src/main/res/drawable/ic_baseline_star_border.xml
  code/app/src/main/res/layout/fragment_nav_experiment_details.xml
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog

#125 Show experiment owner name
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
  code/app/src/main/res/layout/experiment_layout.xml
Labels: enhancement

#121 QR scanner
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/experiment_automata/backend/qr/BinomialQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/CountQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/ExperimentQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/MeasurementQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/NaturalQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRMaker.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRMalformattedException.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/QRCodeManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ViewQRFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java
  code/app/src/main/res/drawable/ic_baseline_qr_code_24.xml
  code/app/src/main/res/layout/fragment_add_binomial_trial.xml
  code/app/src/main/res/layout/fragment_add_count_trial.xml
  code/app/src/main/res/layout/fragment_add_measurement_trial.xml
  code/app/src/main/res/layout/fragment_add_natural_count_trial.xml
  code/app/src/main/res/layout/scanner_activity.xml
  code/app/src/test/java/com/example/experiment_automata/QRTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog

#137 Trial refactoring
  code/app/src/main/java/com/example/experiment_automata/backend/trials/BinomialTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/CountTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/MeasurementTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/NaturalCountTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/Trial.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/test/java/com/example/experiment_automata/TrialTest.java
Labels: Product Backlog, enhancement
