Repository CMPUT301W21T03/Experiment-Automata, pull requests merged in 2021-04, with the labels that each got.

#155 Trial uml
  code/app/src/main/java/com/example/experiment_automata/backend/trials/Trial.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: documentation

#159 Experiment refactoring
  code/app/src/androidTest/java/com/example/experiment_automata/BinomialTrialTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentManagerTestsFireBase.java
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentTestWithFirebase.java
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentMaker.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/location/LocationServices.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRMaker.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/QuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapDisplayFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapUtility.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialsFragment.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentMakerTest.java
  code/app/src/test/java/com/example/experiment_automata/QuestionManagerTest.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: Product Backlog, enhancement

#162 Show the minimum trials needed for an experiment in details screen
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/res/layout/fragment_nav_experiment_details.xml
Labels: Product Backlog

#166 Share qr
  code/app/src/main/AndroidManifest.xml
  code/app/src/main/java/com/example/experiment_automata/backend/qr/BinomialQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/CountQRCode.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ViewQRFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java
  code/app/src/main/res/drawable/ic_baseline_save.xml
  code/app/src/main/res/drawable/ic_baseline_share.xml
  code/app/src/main/res/layout/fragment_display_qr.xml
  code/app/src/main/res/xml/filepaths.xml
Labels: Product Backlog, enhancement

#175 Efficient firebase calls
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: enhancement

#178 Navigate on qr
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScanQRFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java
Labels: enhancement

#180 Clickable contact info
  code/app/src/main/res/layout/fragment_profile.xml
Labels: enhancement

#185 Update experiment list in real-time
  code/app/src/main/java/com/example/experiment_automata/backend/events/OnEventListener.java
  code/app/src/main/java/com/example/experiment_automata/backend/events/UpdateEvent.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/res/values/strings.xml
Labels: enhancement

#194 Barcode testing
  code/app/src/androidTest/java/com/example/experiment_automata/BarcodeManagerTest.java
  code/app/src/androidTest/java/com/example/experiment_automata/BarcodeTest.java
  code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeReference.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScanQRFragment.java
  code/app/src/test/java/com/example/experiment_automata/QRTest.java
Labels: bug, enhancement

#195 Experiment manager refactor
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  doc/uml/UML.png
  doc/uml/uml.puml
Labels: documentation, enhancement

#199 Q&A constraint + frame drop fix
  code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/ReplyArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/SingleQuestionDisplay.java
  code/app/src/main/res/layout/main_question_display.xml
  code/app/src/main/res/layout/reply_layout_list.xml
  code/app/src/main/res/values/dimens.xml
Labels: enhancement

#214 convert plantuml output to svg
  .github/workflows/plantuml.yaml
  doc/uml/UML.png
  doc/uml/UML.svg
Labels: documentation

#217 Add region to experiments
  code/app/src/androidTest/java/com/example/experiment_automata/BinomialTrialTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/LocationTests.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentMaker.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/res/layout/fragment_add_binomial_trial.xml
  code/app/src/main/res/layout/fragment_add_count_trial.xml
  code/app/src/main/res/layout/fragment_add_experiment.xml
  code/app/src/main/res/layout/fragment_add_measurement_trial.xml
  code/app/src/main/res/layout/fragment_add_natural_count_trial.xml
  code/app/src/main/res/layout/fragment_nav_experiment_details.xml
  code/app/src/main/res/layout/fragment_trials.xml
  code/app/src/main/res/values/strings.xml
  code/app/src/test/java/com/example/experiment_automata/BinomialStatsTest.java
  code/app/src/test/java/com/example/experiment_automata/ContactInformationTest.java
  code/app/src/test/java/com/example/experiment_automata/CountStatsTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentMakerTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentManagerTest.java
  code/app/src/test/java/com/example/experiment_automata/ExperimentTest.java
  code/app/src/test/java/com/example/experiment_automata/MeasurementStatTest.java
  code/app/src/test/java/com/example/experiment_automata/NaturalCountStatTest.java
  code/app/src/test/java/com/example/experiment_automata/UserManagerModelTest.java
Labels: Product Backlog

#218 add badges
  README.md
Labels: documentation

#220 Remove Log statements
  code/app/src/main/java/com/example/experiment_automata/backend/barcode/BarcodeManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/NavExperimentDetailsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/home/HomeFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddBinomialTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddCountTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddMeasurementTrialFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/add/AddNaturalCountTrialFragment.java
Labels: enhancement

#222 added updated and new screenshots
  doc/Storyboard/Screens/Add Binomial Trial Loc.png
  doc/Storyboard/Screens/Add Binomial Trial.png
  doc/Storyboard/Screens/Add Count Trial Loc.png
  doc/Storyboard/Screens/Add Count Trial.png
  doc/Storyboard/Screens/Add Experiment.png
  doc/Storyboard/Screens/Add Measurement Trial Loc.png
  doc/Storyboard/Screens/Add Measurement Trial.png
  doc/Storyboard/Screens/Add Natural Count Trial.png
  doc/Storyboard/Screens/Add NaturalCount Trial Loc.png
  doc/Storyboard/Screens/Add Question.png
  doc/Storyboard/Screens/Discussion.png
  doc/Storyboard/Screens/Edit Contact Info.png
  doc/Storyboard/Screens/Edit Experiment.png
  doc/Storyboard/Screens/Hamburger Menu Open.png
  doc/Storyboard/Screens/Make QR Code.png
  doc/Storyboard/Screens/My Experiments.png
  doc/Storyboard/Screens/Published Experiments.png
  doc/Storyboard/Screens/Record Binomial Trial.png
  doc/Storyboard/Screens/Record Count-Based Trial.png
  doc/Storyboard/Screens/Record Measurement Trial.png
  doc/Storyboard/Screens/Record Non-neg int count Trial.png
  doc/Storyboard/Screens/Review Binomial Trial loc.png
  doc/Storyboard/Screens/Review Binomial Trial.png
  doc/Storyboard/Screens/Review Count Based Trial loc.png
  doc/Storyboard/Screens/Review Measurement Trial loc.png
  doc/Storyboard/Screens/Review Measurement Trial.png
  doc/Storyboard/Screens/Review Natural Trial Loc.png
  doc/Storyboard/Screens/Review Non Negative Int Count Loc.png
  doc/Storyboard/Screens/Review Non-neg int count Trial.png
  doc/Storyboard/Screens/Scan QR Code.png
  doc/Storyboard/Screens/Search Experiments.png
  doc/Storyboard/Screens/Subscriptions.png
  doc/Storyboard/Screens/User Profile.png
  doc/Storyboard/Screens/View Count-Based Trial.png
  doc/Storyboard/Screens/View Experiment (Experimenter).png
  doc/Storyboard/Screens/View Experiment (Experimenter)2.png
  doc/Storyboard/Screens/View Experiment (Owner).png
  doc/Storyboard/Screens/View Experiment_ Location warning.png
  doc/Storyboard/Screens/View Locations.png
Labels: documentation

#223 remove known issues
  code/app/src/androidTest/java/com/example/experiment_automata/ExperimentUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/QuestionsUserStoriesTests.java
  code/app/src/androidTest/java/com/example/experiment_automata/SearchUserStoriesTests.java
  code/app/src/main/java/com/example/experiment_automata/backend/events/OnEventListener.java
  code/app/src/main/java/com/example/experiment_automata/backend/events/UpdateEvent.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/BinomialExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/CountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/Experiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/ExperimentType.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/Graphable.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/MeasurementExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/NaturalCountExperiment.java
  code/app/src/main/java/com/example/experiment_automata/backend/experiments/StatSummary.java
  code/app/src/main/java/com/example/experiment_automata/backend/location/LocationServices.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/BinomialQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/CountQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/ExperimentQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/MeasurementQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/NaturalQRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRCode.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRMaker.java
  code/app/src/main/java/com/example/experiment_automata/backend/qr/QRMalformattedException.java
  code/app/src/main/java/com/example/experiment_automata/backend/questions/Question.java
  code/app/src/main/java/com/example/experiment_automata/backend/questions/QuestionManager.java
  code/app/src/main/java/com/example/experiment_automata/backend/questions/Reply.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/BinomialTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/CountTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/MeasurementTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/NaturalCountTrial.java
  code/app/src/main/java/com/example/experiment_automata/backend/trials/Trial.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/ContactInformation.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
  code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
  code/app/src/main/java/com/example/experiment_automata/ui/NavigationActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/AddExperimentFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ExperimentListAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/HistogramFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/ResultsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/experiments/StatisticsFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/EditUserFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/profile/ProfileViewModel.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ScannerActivity.java
  code/app/src/main/java/com/example/experiment_automata/ui/qr/ViewQRFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/AddQuestionFragment.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/QuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/ReplyArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/question/SingleQuestionDisplay.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/MapDisplay/MapUtility.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialsFragment.java
  code/app/src/test/java/com/example/experiment_automata/UserManagerModelTest.java
Labels: documentation

#224 Update README.md
  README.md
Labels: documentation

#229 Ignore trials only owner
  code/app/src/main/java/com/example/experiment_automata/ui/trials/TrialArrayAdapter.java
  code/app/src/main/res/layout/trial_layout.xml
  code/app/src/main/res/values/dimens.xml
Labels: Product Backlog
